
package pl.com.kir.srpn.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgentService", targetNamespace = "http://soap.srpn.kir.com.pl/")
@XmlSeeAlso({
    iso.std.iso._20022.tech.xsd.pacs_002_001.ObjectFactory.class,
    iso.std.iso._20022.tech.xsd.pacs_004_001.ObjectFactory.class,
    iso.std.iso._20022.tech.xsd.pacs_008_001.ObjectFactory.class,
    pl.com.kir.srpn.soap.ObjectFactory.class
})
public interface AgentService {


    /**
     * 
     * @param document
     * @return
     *     returns iso.std.iso._20022.tech.xsd.pacs_002_001.Document
     */
    @WebMethod
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03")
    @RequestWrapper(localName = "acknowledgeDebit", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.AcknowledgeDebit")
    @ResponseWrapper(localName = "acknowledgeDebitResponse", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.AcknowledgeDebitResponse")
    public iso.std.iso._20022.tech.xsd.pacs_002_001.Document acknowledgeDebit(
        @WebParam(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.02")
        iso.std.iso._20022.tech.xsd.pacs_008_001.Document document);

    /**
     * 
     * @param document
     * @return
     *     returns iso.std.iso._20022.tech.xsd.pacs_002_001.Document
     */
    @WebMethod
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03")
    @RequestWrapper(localName = "authorizeTransfer", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.AuthorizeTransfer")
    @ResponseWrapper(localName = "authorizeTransferResponse", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.AuthorizeTransferResponse")
    public iso.std.iso._20022.tech.xsd.pacs_002_001.Document authorizeTransfer(
        @WebParam(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.02")
        iso.std.iso._20022.tech.xsd.pacs_008_001.Document document);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "pong", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.PingResponse")
    public String ping();

    /**
     * 
     * @param document
     * @return
     *     returns iso.std.iso._20022.tech.xsd.pacs_002_001.Document
     */
    @WebMethod
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03")
    @RequestWrapper(localName = "rejectTransfer", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.RejectTransfer")
    @ResponseWrapper(localName = "rejectTransferResponse", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.RejectTransferResponse")
    public iso.std.iso._20022.tech.xsd.pacs_002_001.Document rejectTransfer(
        @WebParam(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.004.001.02")
        iso.std.iso._20022.tech.xsd.pacs_004_001.Document document);

    /**
     * 
     * @param document
     * @return
     *     returns iso.std.iso._20022.tech.xsd.pacs_002_001.Document
     */
    @WebMethod
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03")
    @RequestWrapper(localName = "acknowledgeCredit", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.AcknowledgeCredit")
    @ResponseWrapper(localName = "acknowledgeCreditResponse", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.AcknowledgeCreditResponse")
    public iso.std.iso._20022.tech.xsd.pacs_002_001.Document acknowledgeCredit(
        @WebParam(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.02")
        iso.std.iso._20022.tech.xsd.pacs_008_001.Document document);

}
