
package pl.com.kir.srpn.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgentService", targetNamespace = "http://soap.srpn.kir.com.pl/", wsdlLocation = "file:/D:/zabawy/netbeansprojects/ExpressELIXIR/src/wsdl/AgentService.wsdl")
public class AgentService_Service
    extends Service
{

    private final static URL AGENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException AGENTSERVICE_EXCEPTION;
    private final static QName AGENTSERVICE_QNAME = new QName("http://soap.srpn.kir.com.pl/", "AgentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/zabawy/netbeansprojects/ExpressELIXIR/src/wsdl/AgentService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENTSERVICE_WSDL_LOCATION = url;
        AGENTSERVICE_EXCEPTION = e;
    }

    public AgentService_Service() {
        super(__getWsdlLocation(), AGENTSERVICE_QNAME);
    }

    public AgentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENTSERVICE_QNAME, features);
    }

    public AgentService_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENTSERVICE_QNAME);
    }

    public AgentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENTSERVICE_QNAME, features);
    }

    public AgentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgentService
     */
    @WebEndpoint(name = "AgentServicePort")
    public AgentService getAgentServicePort() {
        return super.getPort(new QName("http://soap.srpn.kir.com.pl/", "AgentServicePort"), AgentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgentService
     */
    @WebEndpoint(name = "AgentServicePort")
    public AgentService getAgentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.srpn.kir.com.pl/", "AgentServicePort"), AgentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENTSERVICE_EXCEPTION!= null) {
            throw AGENTSERVICE_EXCEPTION;
        }
        return AGENTSERVICE_WSDL_LOCATION;
    }

}
