
package pl.com.kir.srpn.soap;

import javax.xml.ws.WebFault;
import com.bea.wli.sb.context.FaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://soap.srpn.kir.com.pl/")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Fault(String message, FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Fault(String message, FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bea.wli.sb.context.FaultType
     */
    public FaultType getFaultInfo() {
        return faultInfo;
    }

}
