
package pl.com.kir.srpn.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SRPNService", targetNamespace = "http://soap.srpn.kir.com.pl/")
@XmlSeeAlso({
    com.bea.wli.sb.context.ObjectFactory.class,
    iso.std.iso._20022.tech.xsd.pacs_002_001.ObjectFactory.class,
    iso.std.iso._20022.tech.xsd.pacs_008_001.ObjectFactory.class,
    pl.com.kir.srpn.soap.ObjectFactory.class
})
public interface SRPNService {


    /**
     * 
     * @param document
     * @return
     *     returns iso.std.iso._20022.tech.xsd.pacs_002_001.Document
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03")
    @RequestWrapper(localName = "sendTransfer", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.SendTransfer")
    @ResponseWrapper(localName = "sendTransferResponse", targetNamespace = "http://soap.srpn.kir.com.pl/", className = "pl.com.kir.srpn.soap.SendTransferResponse")
    public iso.std.iso._20022.tech.xsd.pacs_002_001.Document sendTransfer(
        @WebParam(name = "Document", targetNamespace = "urn:iso:std:iso:20022:tech:xsd:pacs.008.001.02")
        iso.std.iso._20022.tech.xsd.pacs_008_001.Document document)
        throws Fault
    ;

}
