//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 02:34:50 PM CEST 
//


package pl.com.kir.srpn.soap.availability;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GivenDateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GivenDateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="givenDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="unavailableFrom" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="unavailableTo" use="required" type="{http://www.w3.org/2001/XMLSchema}time" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GivenDateType")
public class GivenDateType {

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar givenDate;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar unavailableFrom;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar unavailableTo;

    /**
     * Gets the value of the givenDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGivenDate() {
        return givenDate;
    }

    /**
     * Sets the value of the givenDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGivenDate(XMLGregorianCalendar value) {
        this.givenDate = value;
    }

    /**
     * Gets the value of the unavailableFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUnavailableFrom() {
        return unavailableFrom;
    }

    /**
     * Sets the value of the unavailableFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUnavailableFrom(XMLGregorianCalendar value) {
        this.unavailableFrom = value;
    }

    /**
     * Gets the value of the unavailableTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUnavailableTo() {
        return unavailableTo;
    }

    /**
     * Sets the value of the unavailableTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUnavailableTo(XMLGregorianCalendar value) {
        this.unavailableTo = value;
    }

}
