//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 02:34:50 PM CEST 
//


package pl.com.kir.srpn.soap.availability;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgentAvailabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgentAvailabilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BranchList" type="{http://soap.srpn.kir.com.pl/availability}BranchListType"/>
 *         &lt;element name="StaticAvailibilityTableSending" type="{http://soap.srpn.kir.com.pl/availability}StaticAvailibilityTableType"/>
 *         &lt;element name="StaticAvailibilityTableReceiving" type="{http://soap.srpn.kir.com.pl/availability}StaticAvailibilityTableType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgentAvailabilityType", propOrder = {
    "branchList",
    "staticAvailibilityTableSending",
    "staticAvailibilityTableReceiving"
})
public class AgentAvailabilityType {

    @XmlElement(name = "BranchList", required = true)
    protected BranchListType branchList;
    @XmlElement(name = "StaticAvailibilityTableSending", required = true)
    protected StaticAvailibilityTableType staticAvailibilityTableSending;
    @XmlElement(name = "StaticAvailibilityTableReceiving", required = true)
    protected StaticAvailibilityTableType staticAvailibilityTableReceiving;

    /**
     * Gets the value of the branchList property.
     * 
     * @return
     *     possible object is
     *     {@link BranchListType }
     *     
     */
    public BranchListType getBranchList() {
        return branchList;
    }

    /**
     * Sets the value of the branchList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchListType }
     *     
     */
    public void setBranchList(BranchListType value) {
        this.branchList = value;
    }

    /**
     * Gets the value of the staticAvailibilityTableSending property.
     * 
     * @return
     *     possible object is
     *     {@link StaticAvailibilityTableType }
     *     
     */
    public StaticAvailibilityTableType getStaticAvailibilityTableSending() {
        return staticAvailibilityTableSending;
    }

    /**
     * Sets the value of the staticAvailibilityTableSending property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticAvailibilityTableType }
     *     
     */
    public void setStaticAvailibilityTableSending(StaticAvailibilityTableType value) {
        this.staticAvailibilityTableSending = value;
    }

    /**
     * Gets the value of the staticAvailibilityTableReceiving property.
     * 
     * @return
     *     possible object is
     *     {@link StaticAvailibilityTableType }
     *     
     */
    public StaticAvailibilityTableType getStaticAvailibilityTableReceiving() {
        return staticAvailibilityTableReceiving;
    }

    /**
     * Sets the value of the staticAvailibilityTableReceiving property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticAvailibilityTableType }
     *     
     */
    public void setStaticAvailibilityTableReceiving(StaticAvailibilityTableType value) {
        this.staticAvailibilityTableReceiving = value;
    }

}
