//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 02:34:50 PM CEST 
//


package pl.com.kir.srpn.soap.availability;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.com.kir.srpn.soap.availability package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AgentAvailabilityReport_QNAME = new QName("http://soap.srpn.kir.com.pl/availability", "AgentAvailabilityReport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.com.kir.srpn.soap.availability
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PeriodDayType }
     * 
     */
    public PeriodDayType createPeriodDayType() {
        return new PeriodDayType();
    }

    /**
     * Create an instance of {@link BranchListType }
     * 
     */
    public BranchListType createBranchListType() {
        return new BranchListType();
    }

    /**
     * Create an instance of {@link PeriodListType }
     * 
     */
    public PeriodListType createPeriodListType() {
        return new PeriodListType();
    }

    /**
     * Create an instance of {@link AgentAvailabilityReportType }
     * 
     */
    public AgentAvailabilityReportType createAgentAvailabilityReportType() {
        return new AgentAvailabilityReportType();
    }

    /**
     * Create an instance of {@link PeriodMonthType }
     * 
     */
    public PeriodMonthType createPeriodMonthType() {
        return new PeriodMonthType();
    }

    /**
     * Create an instance of {@link GivenDateType }
     * 
     */
    public GivenDateType createGivenDateType() {
        return new GivenDateType();
    }

    /**
     * Create an instance of {@link AgentAvailabilityType }
     * 
     */
    public AgentAvailabilityType createAgentAvailabilityType() {
        return new AgentAvailabilityType();
    }

    /**
     * Create an instance of {@link StaticAvailibilityTableType }
     * 
     */
    public StaticAvailibilityTableType createStaticAvailibilityTableType() {
        return new StaticAvailibilityTableType();
    }

    /**
     * Create an instance of {@link BranchType }
     * 
     */
    public BranchType createBranchType() {
        return new BranchType();
    }

    /**
     * Create an instance of {@link PeriodWeekType }
     * 
     */
    public PeriodWeekType createPeriodWeekType() {
        return new PeriodWeekType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentAvailabilityReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://soap.srpn.kir.com.pl/availability", name = "AgentAvailabilityReport")
    public JAXBElement<AgentAvailabilityReportType> createAgentAvailabilityReport(AgentAvailabilityReportType value) {
        return new JAXBElement<AgentAvailabilityReportType>(_AgentAvailabilityReport_QNAME, AgentAvailabilityReportType.class, null, value);
    }

}
