//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.25 at 02:34:50 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.srpn.kir.com.pl/availability", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.com.kir.srpn.soap.availability;
